### ISSUE TITLE
Long entry string too long

### ISSUE THREAD

**Issue by cfdynamics01** [OWASP/www-project-winfim.net#3]
Occasionally getting an error the the entry exceeds 32766 characters.  I think its possibly related to the number of connections to the server during the "Established Remote Connection" scan. Any way to truncate that so it no longer throws an error?

Exception : Log entry string is too long. A string written to the event log cannot exceed 32766 characters.
Please make sure all input entries are correct under "monlist.txt", "exclude_path.txt" and "exclude_extension.txt".
Please restart the service after correction.

**Comment by mpowrie** [comment]
Hi @cfdynamics01 

Pull request https://github.com/OWASP/www-project-winfim.net/pull/4 will hopefully resolve this issue:
A 32766 character limit has been placed on Windows event log entries.
Also - a new flag in file `WinFIM.NET Service.exe.config` called `is_capture_remote_connection_status` has been set to control whether remote connection status is logged on each run - it now defaults to `false` but can be enabled.

**Comment by mpowrie** [comment]
Pull request https://github.com/OWASP/www-project-winfim.net/pull/4 has been merged. Let us know if the issue is solved in version [1.2.0](https://github.com/OWASP/www-project-winfim.net/releases/tag/v1.2.0).

**Comment by cfdynamics01** [comment]
Looks like that issue is resolved.  Thank you!
