### ISSUE TITLE
Exclusion errors

### ISSUE THREAD

**Issue by cfdynamics01** [OWASP/www-project-winfim.net#5]
Trying to get certain folders excluded since they are constantly changing and creating a lot of unnecessary alerts.  Seeing errors for excluded directories that are definitely there:
{"Timestamp":"2022-10-28T10:44:28.1416137-05:00","Level":"Error","MessageTemplate":"Exclusion error:Could not find a part of the path 'C:\\Windows\\System32\\winevt\\Logs\\'."}
{"Timestamp":"2022-10-28T10:44:28.1426138-05:00","Level":"Error","MessageTemplate":"Exclusion error:Could not find file 'C:\\Windows\\System32\\WDI\\LogFiles\\'."}

Also a question about exclusions.  When you exclude a directory, does it also exclude any sub directories below the path?

**Comment by mpowrie** [comment]
Thanks @cfdynamics01 for the bug report.
I'll create a Pull Request to address this issue.
If you exclude a directory, all subdirectories below the path are also excluded.

**Comment by mpowrie** [comment]
Pull Request https://github.com/OWASP/www-project-winfim.net/pull/7 looks to have solved this problem, when it get's merged
