### ISSUE TITLE
Avoid creating unnecessary processes

### ISSUE THREAD

**Issue by slang25** [OWASP/www-project-winfim.net#6]
Hello 👋 

When deploying WinFIM.NET, I've noticed that we have lots of event log audit entries around the creation of processes (`cmd.exe`, `netstat.exe`, `qprocess.exe`). Would you be happy to receive PRs to avoid process creation and to use the underlying APIs where appropriate?

I can add some detail in the individual PRs.

**Comment by mpowrie** [comment]
Hi @slang25,

I'd love to see some PRs addressing this. While not the repo owner, I've been contributing PRs to the project.

**Comment by slang25** [comment]
Thanks @mpowrie 🙂 

I've made a start in #7, I've also locally got the beginnings of reworking `GetRemoteConnections` to avoid `netstat.exe` and `qprocess.exe` which I'll continue to work on.
